use_frameworks!

platform :ios, '9.0'

target 'Web3-Swift_Example' do
  pod 'Web3-Swift', :path => '../'

  target 'Web3-Swift_Tests' do
    inherit! :search_paths

#    pod 'Quick', '~> 2.2.0'
#    pod 'Nimble', '~> 8.0.7'
  end
end
